name: Shrine
description: Learn the basics of using Material Components by building a simple app with core components.

dependencies:
  dio: 2.1.1
  random_string: ^1.1.0
  firebase_auth: ^0.11.1+8
  cached_network_image: ^1.1.1
  firebase_messaging: ^5.1.8
  flutter:
    sdk: flutter
  intl: ^0.15.6

  cupertino_icons: ^0.1.0
  shrine_images: 1.1.1

dev_dependencies:

  toast: ^0.1.5
  url_launcher: ^4.2.0+3
  cloud_firestore : 0.12.7
  firebase_database: 3.0.4
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  image_path_android: "assets/launcher/Icon2.png"
  image_path_ios: "assets/launcher/Icon2.png"
  adaptive_icon_background: "assets/launcher/Iconbackground.png"
  adaptive_icon_foreground: "assets/launcher/foreground2.png"



flutter_test:
    sdk: flutter


flutter:
  # TODO: Insert Fonts (103)
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
          weight: 400
    - family: Josefin Sans
      fonts:
        - asset: fonts/JosefinSans-SemiBold.ttf
          weight: 400

  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/address.png
    - assets/fb.png
    - assets/tel.png
    - assets/wtsp.png
    - assets/wtsp50.png
    - assets/mosaic_logo.png
    - assets/fraise.jpg
    - assets/decor.jpg
    - assets/tiles.jpg
    - assets/background.png
