name: Shrine
description: Learn the basics of using Material Components by building a simple app with core components.

dependencies:
  dio: 2.1.1
  random_string: ^1.1.0
  firebase_auth: ^0.11.1+8
  flutter:
    sdk: flutter
  intl: ^0.15.6

  cupertino_icons: ^0.1.0
  shrine_images: 1.1.1

dev_dependencies:

  toast: ^0.1.5
  url_launcher: ^4.2.0+3
  cloud_firestore : 0.12.7
  firebase_database: 3.0.4
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/MTicon.png"



flutter_test:
    sdk: flutter


flutter:
  # TODO: Insert Fonts (103)
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500

  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/tiles.jpg
    - assets/background.png
    - assets/fraise.jpg
    - assets/decor.jpg
    - assets/address.png
    - assets/fb.png
    - assets/tel.png
    - assets/wtsp.png
    - assets/wtsp50.png

