name: Shrine

dependencies:

  firebase_auth: ^0.11.1+8
  flutter:
    sdk: flutter
  intl: ^0.15.6




dev_dependencies:

  toast: ^0.1.5
  cloud_firestore : 0.12.7
  firebase_database: 3.0.4
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.2+1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path:  "assets/icon/MTicon.png"


flutter:
  # TODO: Insert Fonts (103)
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500

  uses-material-design: true
  assets:

    - assets/tiles.jpg
    - assets/background.png
    - assets/fraise.jpg
    - assets/decor.jpg
    - assets/icon/MTicon.png